### PR TITLE
Add complete dev server infrastructure

### PR DESCRIPTION
**Pull request by gsfr**
Add paster-based dev infrastructure. App is served at http://localhost:8080/app, by default.

To do:
- [x] Change branch name for `git clone` of scitran/api to aloha when scitran/api#102 lands.

Open issues:
- [x] Google OAuth prompts for "offline access" at every login.

### CODE REVIEW

**Comment by josschne** [comment]
@gsfr I like that we're now freezing versions, but I was actually hoping we could get away from the complexity of all the separate requirements files. Thoughts?

**Comment by gsfr** [comment]
@josschne Yes, agreed. But note that this is for tying a final bow on SDM to close out our grant. Please consider it out-of-scope.

**Comment by josschne** [comment]
:+1:  LGTM

**Comment by rentzso** [comment]
the  google oauth issue is related to the redirect host.
If it is localhost, Google will always ask for offline access:
http://stackoverflow.com/a/31242454/1186555

workaround:
I have created two entries to allow redirects from scitran.edu
add a line in /etc/hosts "127.0.0.1   scitran.edu"
open app at http://scitran.edu:8080/app

**Pull request merged**
